# Generated by Django 2.2.6 on 2019-12-01 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('B', 'bus'), ('T', 'train')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(default=1)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('N', 'normal'), ('W', 'weekend'), ('H', 'holiday')], default='N', max_length=1)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TimeField(default=datetime.datetime.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Service')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Station')),
            ],
        ),
        migrations.CreateModel(
            name='StationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Line')),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='tripplanner.Station')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='tripplanner.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DurationField(default=datetime.timedelta)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.TimetableData')),
            ],
        ),
    ]
