# Generated by Django 2.2.6 on 2019-11-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(default=1)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpos', models.FloatField(default=0.0)),
                ('ypos', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='StationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Service')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('station_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.StationOrder')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Timetable')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='stations',
            field=models.ManyToManyField(through='tripplanner.StationOrder', to='tripplanner.Station'),
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.TimeField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.Timetable')),
            ],
        ),
    ]
