# Generated by Django 2.2.6 on 2019-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='name',
            field=models.TextField(default='A', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.TextField(default='A', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stationorder',
            name='order_num',
            field=models.IntegerField(),
        ),
    ]
