# Generated by Django 2.2.6 on 2019-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0004_auto_20191113_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledata',
            name='date_time',
            field=models.TimeField(),
        ),
    ]
