# Generated by Django 2.2.6 on 2019-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0005_auto_20191117_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabledata',
            name='type',
            field=models.CharField(choices=[('N', 'normal'), ('W', 'weekend'), ('H', 'holiday')], default='N', max_length=1),
        ),
    ]
