# Generated by Django 2.2.6 on 2019-11-22 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0007_auto_20191122_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabledata',
            name='delay',
        ),
        migrations.AddField(
            model_name='service',
            name='valid_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='service',
            name='valid_until',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DurationField(default=datetime.timedelta)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripplanner.TimetableData')),
            ],
        ),
    ]
