# Generated by Django 2.2.6 on 2019-11-23 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0008_auto_20191122_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabledata',
            name='station_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetabledata',
            name='date_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
