# Generated by Django 2.2.6 on 2019-11-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0009_auto_20191123_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabledata',
            name='station_num',
        ),
    ]
