# Generated by Django 2.2.6 on 2019-11-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0010_remove_timetabledata_station_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='type',
            field=models.CharField(choices=[('B', 'bus'), ('T', 'train')], default='T', max_length=1),
        ),
    ]
